---
- name: Replicape - Install Klipper
  include: replicape.yml
  when: platform == 'replicape'
  dependencies:
    - role: linux_preparation

- name: Recore - Install Klipper
  include: recore.yml
  when: platform == 'recore'
  dependencies:
    - role: linux_preparation