---
- name: remove login info
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/issue.net
    - /etc/issue

- name: Register ReFactor version
  script:
    cmd: '{{ role_path }}/files/get_refactor_version.sh'
  register: version

- name: upgrade packages
  apt:
    upgrade: dist

- name: remove unneeded packages
  apt:
    pkg:
    - nginx
    - hostapd
    - libgtk3-common
    - grub
    - javascript-common
    state: absent
    autoremove: yes

- name: install debconf-utils and curl
  apt:
    pkg:
      - debconf-utils
      - curl
      - firmware-realtek
      - git
      - usbutils
    state: present

- name: Replicape - update RCN scripts
  shell:
    chdir: /opt/scripts
    cmd: |
      chown -R root /opt/scripts
      git pull

- name: update package list
  apt:
    update_cache: yes

- name: install packages
  apt:
    pkg:
    - unzip
    - libavahi-compat-libdnssd1
    - libnss-mdns
    - byobu
    - htop
    - cpufrequtils
    - pkg-config
    state: present
    autoremove: yes
    autoclean: yes

- name: enable root login via ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PermitRootLogin yes'
    state: present

- name: remove unneeded files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apache2/
    - /root/.c9
    - /usr/lib/node_modules
    - /usr/local/lib/node_modules
    - /var/lib/cloud9
    - /var/cache/doc*

- name: create dogtag
  file:
    path: '/etc/{{ dogtag }}'
    state: touch

- name: get date
  command: 'date --iso-8601'
  register: build_date

- name: write dogtag
  lineinfile:
    line: '{{ version.stdout }} {{ build_date.stdout }}'
    state: present
    path: '/etc/{{ dogtag }}'

- name: remove hostname
  file:
    path: /etc/hostname
    state: absent

- name: create hostname
  file:
    path: /etc/hostname
    state: touch

- name: set hostname
  lineinfile:
    path: /etc/hostname
    line: '{{ platform }}'

- name: set root password
  user:
    name: root
    password: "{{ 'kamikaze' | password_hash('sha512') }}"

- name: force user to change debian password on first login
  shell:
    cmd: "chage -d 0 debian"

- name: force user to change root password on first login
  shell:
    cmd: "chage -d 0 root"

- name: create issue and issue.net file
  file:
    path: '{{ item }}'
    state: touch
  with_items:
   - /etc/issue
   - /etc/issue.net

- name: write issue and issue.net
  copy:
    dest: '{{ item }}'
    content: |
      {{ version.stdout }}

      Check that nothing is printing before any intensive operation!
  with_items:
    - /etc/issue.net
    - /etc/issue

- name: enable ssh
  service:
    name: ssh
    enabled: yes

- name: remove connman
  apt:
    name: connman
    state: absent

- name: create resolv.conf
  file:
    path: /etc/resolv.conf
    state: touch
    mode: 0644
    owner: root
    group: root

- name: reset the resolv.conf file
  lineinfile:
    path: /etc/resolv.conf
    line: nameserver 1.1.1.1
    state: present

- name: install NetworkManager
  apt:
    name: network-manager
    state: latest

- name: Disable audio
  lineinfile:
    path: /boot/uEnv.txt
    line: disable_uboot_overlay_audio=1
    state: present

- name: Reflash pru firmware
  command:
    chdir: /home/debian/klipper
    cmd: ./scripts/flash-pru.sh

- name: Replicape - fix home ownership
  command: chown -R debian:debian /home/debian
