#!/bin/bash
systemctl disable octoprint
systemctl stop octoprint

systemctl disable nftables
systemctl stop nftables

systemctl enable nginx
systemctl start nginx

systemctl enable moonraker
systemctl start moonraker
