---
- name: Replicape - Install Mjpg
  include: replicape.yml
  when: platform == 'replicape'

- name: Recore - Install Mjpg
  include: recore.yml
  when: platform == 'recore'

- name: Pi - Install Mjpg
  include: pi.yml
  when: platform == 'pi'

- name: Pi64 - Install Mjpg
  include: pi.yml
  when: platform == 'pi64'
