appearance:
  name: KAMIKAZE
folder:
  uploads: /usr/share/models
plugins:
  softwareupdate:
    _config_version: 9
    checks:
      octoprint:
        checkout_folder: /home/debian/OctoPrint
        prerelease: false
server:
  firstRun: true
  commands:
    serverRestartCommand: sudo systemctl restart octoprint.service
    systemRestartCommand: sudo reboot
    systemShutdownCommand: sudo shutdown -h now
webcam:
  stream: http://recore.local:8080/?action=stream
  snapshot: http://recore.local:8080/?action=snapshot
  ffmpeg: /usr/bin/avconv
serial:
    additionalPorts:
    - /tmp/printer
    port: /tmp/printer
