#!/bin/bash

set -e

if test -f /dev/ttyS4; then
        FLASH_DEVICE=/dev/ttyS4
else
        FLASH_DEVICE=/dev/ttyS2
fi

STM32_BINARY=/opt/firmware/stm32.bin

systemctl stop klipper

gpioset 1 197=1
gpioset 1 196=0
gpioset 1 196=1
stm32flash -w ${STM32_BINARY} -v -g 0 ${FLASH_DEVICE}
gpioset 1 197=0
gpioget 1 196

systemctl disable flash-stm32
systemctl start klipper
