---
- name: Add the Toggle build repo for apt packages
  apt_repository:
    repo: deb [arch=arm64] http://feeds.iagent.no/ubuntu xenial main
    state: present
    filename: thingprinter


- name: Replicape - Install Toggle
  include: replicape.yml
  when: platform == 'replicape'

- name: Recore - Install Toggle
  include: recore.yml
  when: platform == 'recore'

- name: Pi - Install Toggle
  include pi.yml
  when: platform == 'pi'

- name: Pi64
  include: pi.yml
  when: platform == 'pi64'
