---
- name: add iagent feeds
  apt_key:
    url: http://feeds.iagent.no/debian/iagent.public.key
    state: present

- name: Add specified repository into sources list
  apt_repository:
    repo: deb [arch=arm64] http://feeds.iagent.no/debian buster main
    state: present

- name: update package list
  apt:
    update_cache: yes

- name: install dependencies
  apt:
    pkg:
      - python3-setuptools
      - python3-gi
      - python3-pip
      - python3-dev
      - libdbus-1-dev
      - libglib2.0-dev
      - python3-cairo
      - python3-gi-cairo
      - python3-networkmanager
      - python3-tornado
      - python3-requests
      - gir1.2-mx-2.0-0
      - gir1.2-mash-0.3-0
    state: present
    force: yes

- name: clone toggle from git
  git:
    repo: https://github.com/intelligent-agent/toggle
    dest: '{{ toggle_home }}'
    depth: 1

- name: copy toggle service file
  copy:
    src: '{{ role_path }}/files/toggle_recore.service'
    dest: /etc/systemd/system/toggle.service

- name: grant sudo to debian user for restarting toggle service
  lineinfile:
    path: /etc/sudoers.d/debian
    line: '%debian ALL=NOPASSWD: /bin/systemctl restart toggle.service'
    state: present

- name: Use pip to install toggle
  pip:
    chdir: '{{ toggle_home }}'
    requirements: '{{ toggle_home }}/requirements.txt'
    executable: pip3

- name: Use pip to install toggle data files
  shell:
    chdir: "{{ toggle_home }}"
    cmd: "python3 setup.py install_data"

- name: Set up the local.cfg file
  copy:
    dest: /etc/toggle/local.cfg
    owner: debian
    group: debian
    content: |
      [OctoPrint]
      user = toggle
      authentication =

- name: enable the toggle service
  block:
    - name: Attempt to enable toggle with systemd module
      systemd:
        name: toggle
        daemon_reload: yes
        enabled: yes
  rescue:
    - name: Fallback to shell
      shell: systemctl enable toggle

- name: Recore - copy toggle-runfirst service file
  copy:
    src: '{{ role_path }}/files/toggle-runfirst.service'
    dest: /etc/systemd/system/toggle-runfirst.service

- name: Recore - Script - install toggle-runfirst
  copy:
    src: '{{ role_path }}/files/toggle-runfirst'
    dest: /usr/lib/
    mode: +x

- name: Recore - enable the toggle-runfirst service
  block:
    - name: Attempt to enable toggle-runfirst service normally
      systemd:
        name: toggle-runfirst
        daemon_reload: yes
        enabled: yes
  rescue:
    - name: Fallback to shell
      shell: systemctl enable toggle-runfirst
